Django-quiz-app/config/urls.py
from django.contrib import admin
from django.urls import path, include

# Static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizes.urls', namespace='quizes'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Django-quiz-app/quizes/urls.py
from django.urls import path

from .views import (
    QuizListView,
    QuizDetailView,
    quiz_detail_data_view,
    save_quiz_view
)

app_name = 'quizes'

urlpatterns = [
    path('', QuizListView.as_view(), name='quiz_list_view'),
    path('quiz/<pk>', QuizDetailView.as_view(), name='quiz_view'),
    path('quiz/<pk>/data', quiz_detail_data_view, name='quiz_data_view'),
    path('quiz/<pk>/save', save_quiz_view, name='quiz_save_view'),
]

Django-quiz-app/questions/models.py
from operator import mod
from pyexpat import model
from django.db import models
from quizes.models import Quiz

# Create your models here.
class Question(models.Model):
    
    text = models.TextField()
    
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        related_name="questions",
    )
    
    date = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=True
    )

    def __str__(self):
        """
        How the Question is displayed in the Admin page
        """
        return f"{self.pk} - {str(self.text)[:10]}"

    @property
    def get_answers(self):
        return self.answers.all()


class Answer(models.Model):
    """
    The answer options to the Question model.
    It can be true or false.
    """
  
    text = models.TextField()
    
    date = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=True
    )

    correct = models.BooleanField(default=False)
 
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name="answers"
    )

    def __str__(self):
        return f"Question: {str(self.question.text)[:15]}, Ans: {str(self.text)[:10]}, Correct: {self.correct}"
    

Django-quiz-app/quizes/models.py
"""
Models of the Quizes app
"""
import random
from django.db import models

# Validators
from validators.validators import PERCENTAGE_VALIDATOR


DIFFICULTY_CHOICES = (
    ("Easy", "Easy"),
    ("Medium", "Medium"),
    ("Hard", "Hard"),
)

# Topic class
class Topic(models.Model):
    """Topic: The topic of the quizes
    """

    name = models.CharField(max_length=120)
    
    description = models.TextField(
        default="Programming",
        blank=True,
        null=True
    )

    date = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=True
    )

    def __str__(self):
        """
        Show the topic name in the Admin page
        """
        return self.name


# Quiz model
class Quiz(models.Model):
    """Quiz: The base of our app
    """

    name = models.CharField(max_length=150)

    description = models.TextField(
        default="Another quiz!",
        blank=True,
        null=True
    )

    date = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=True
    )

    topic = models.ForeignKey(
        Topic,
        on_delete=models.SET_NULL,
        help_text="The topic the quiz will be evaluating about",
        null=True,
        blank=True,
        related_name="quizes" # The way we reference the quiz using a Topic object
    )

    number_of_questions = models.IntegerField()

    time = models.IntegerField(
        help_text="Duration of the quiz in minutes"
    )

    
    required_score = models.DecimalField(
        help_text="Score needed to pass the quiz in %",
        max_digits=6,
        decimal_places=2,
        validators=PERCENTAGE_VALIDATOR
    )

    difficulty = models.CharField(
        help_text="The difficulty of the quiz",
        max_length=6,
        choices=DIFFICULTY_CHOICES
    )

    def __str__(self):
        return f"{self.name} - {self.topic.name}"

    @property
    def get_questions(self):
        questions = list(self.questions.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = "Quizes"

Django-quiz-app/results/models.py
from django.db import models

# Quiz model        
from quizes.models import Quiz

# User model
from django.contrib.auth.models import User

# Validators
from validators.validators import PERCENTAGE_VALIDATOR


# Result model
class Result(models.Model):
    """
    The results for the quiz answers of a given user
    """ 
    
    date = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=True
    )

    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )

    score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        default=0,
        validators=PERCENTAGE_VALIDATOR
    )

    
    def __str__(self):
        return str(self.user)

Django-quiz-app/questions/views.py
from django.shortcuts import render

# Create your views here.

Django-quiz-app/quizes/views.py
from django.views.generic import ListView, DetailView
from django.http import JsonResponse
from results.models import Result
from questions.models import Question, Answer
from .models import Quiz


# Quiz List view
class QuizListView(ListView):
    model = Quiz
    template_name = 'quizes/main.html'

class QuizDetailView(DetailView):
    model = Quiz
    template_name = 'quizes/detail.html'

def quiz_detail_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for question in quiz.get_questions:
        answers = []
        for answer in question.get_answers:
            answers.append(answer.text)
        questions.append({question.text: answers})
    
    return JsonResponse({
        'data': questions,
        'time': quiz.time
    })

def save_quiz_view(request, pk):
    if request.accepts("application/json"):
        data = request.POST
        data_ = dict(data.lists())
        data_.pop('csrfmiddlewaretoken')

        questions = []

        for k in data_.keys():
            question = Question.objects.get(text=k)
            questions.append(question)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        required_score = quiz.required_score
        score = 0
        multiplier = 100 / len(questions) 
        results = []

        for q in questions:
            a_selected = data[q.text]

            if a_selected != '':
                correct_answer = Answer.objects.filter(question=q).get(correct=True)
                if a_selected == correct_answer.text:
                    score += 1
                
                results.append({q.text: {
                    'correct_answer': correct_answer.text,
                    'answered': a_selected
                }})
            else:
                results.append({q.text: 'not answered'})

        final_score = score * multiplier


        Result.objects.create(quiz=quiz, user=user, score=final_score)

        json_response = {
            'score': final_score,
            'correct_questions': score,
            'passed': False,
            'required_score': required_score,
            'results': results
        }

        if final_score >= required_score:
            json_response['passed'] = True
            return JsonResponse(json_response)    

        return JsonResponse(json_response)

Django-quiz-app/results/views.py
from django.shortcuts import render

# Create your views here.

Django-quiz-app/quizes/templates/quizes/detail.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}

<script src="{% static 'quizes/quiz.js' %}" defer></script>

{% endblock scripts %}

{% block title %}{{object.name}}{% endblock title %}


{% block content %}


<div class="container text-center py-4">
    <h1 class="">Quiz: {{object.name}}</h1>
</div>

<div class="row">
    <div class="col">
        <div class="text-secondary my-auto" id="score-box">
            <p>Required score: {{object.required_score}} %</p>
        </div>
    </div>
    <div class="col text-end" id="timer-box">
    </div>
</div>

<div class="py-3">
    <a href="{% url 'quizes:quiz_list_view' %}" class="btn btn-danger" id="">
        Go back
    </a>
</div>

<form class="mt-3" id="quiz-form">
    {% csrf_token %}
    <div id="quiz-box" class="">
    </div>
    <div class="text-center py-3">
        <button type="submit" class="mt-4 btn btn-primary btn-lg">Send</button>
    </div>
</form>

<div id="result-box">

</div>

{% endblock content %}

Django-quiz-app/quizes/templates/quizes/main.html
{% extends 'base.html' %}
{% load static %}


{% block scripts %}

<script src="{% static 'quizes/quizes.js' %}" defer></script>

{% endblock scripts %}


{% block title %}Home{% endblock title %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Start Quiz</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-body-confirm">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" id="start-button">Start</button>
            </div>
        </div>
    </div>
</div>

<div class="">
    <h1 class="h1">
        Quiz List
    </h1>
</div>

<hr>

{% for object in object_list %}
<div class="m-3">

    <button type="button" class="btn btn-link modal-button" data-pk="{{object.pk}}" data-date="{{object.date}}"
        data-name="{{object.name}}" data-description="{{object.description}}" data-topic="{{object.topic.name}}"
        data-questions="{{object.number_of_questions}}" data-difficulty="{{object.difficulty}}"
        data-time="{{object.time}}" data-pass="{{object.required_score}}" data-bs-toggle="modal"
        data-bs-target="#quizStartModal">
        {{object.name}}
    </button>
</div>
{% endfor %}

{% endblock content %}

Django-quiz-app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- favicon -->
        {% comment %}
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" /> {% endcomment %}
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <!-- jquery -->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

        <!-- custom css & js-->
        <link rel="stylesheet" href={% static 'css/style.css' %}>
         <script src="{% static 'js/script.js' %}"></script>
        {% block scripts %}
        {% endblock scripts %}

        <title>Quiz app | {% block title %}{% endblock title %}</title>
    </head>

    <body>
        <div class="container mt-3">
            {% block content %}
            {% endblock content %}
        </div>

        <!-- Bootstrap JS -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
        </script>
    </body>

</html>

Django-quiz-app/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="Yinka Enoch Adedokun">
        <link rel="stylesheet" href="css/style2.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
        <title>Login Page</title>
      </head>
      
      <body>
        <div class="box">
            <h2>Contact Info</h2>
            <form>
              <div class="inputBox">
                <input type="text" name="" required="">
                <label>Name</label>
              </div>
              <div class="inputBox">
                <input type="text" name="" required="">
                <label>Surname</label>
              </div>
              <div class="inputBox">
                <input type="tel" name="" required="" placeholder="">
                <label>Phone number +998</label>
              </div>
              <input type="submit" name="" value="Submit">
            </form>
          </div>
      </body>
</html>